using System.Collections.Generic;

public static class PermissionDatabase {
    public enum CommandPermission {
        Cashier,
        General,
        Manager,
        Restocker,
        Text,
        Security
    }

    public static readonly Dictionary<string, CommandPermission> CommandPermissions = new() {
        { "AchievementsManager.InvokeUserCode_CmdAddAchievementPoint__Int32__Int32", CommandPermission.General },
        { "AchievementsManager.InvokeUserCode_CmdMaxFundsCheckouted__Single", CommandPermission.General },
        { "AchievementsManager.InvokeUserCode_CmdRequestGachaponSphere__Int32", CommandPermission.General },
        { "AchievementsManager.InvokeUserCode_CmdRequestGachaponDeletion__GameObject", CommandPermission.General },
        { "CardboardBaler.InvokeUserCode_CmdAddBoxToBaler", CommandPermission.General },
        { "Data_Container.InvokeUserCode_CmdUpdateArrayValues__Int32__Int32__Int32", CommandPermission.General },
        { "Data_Container.InvokeUserCode_CmdContainerClear__Int32", CommandPermission.General },
        { "Data_Container.InvokeUserCode_CmdUpdateArrayValuesStorage__Int32__Int32__Int32", CommandPermission.General },
        { "Data_Container.InvokeUserCode_CmdActivateCashMethod__Int32", CommandPermission.General },
        { "Data_Container.InvokeUserCode_CmdActivateCreditCardMethod", CommandPermission.General },
        { "Data_Container.InvokeUserCode_CmdReceivePayment__Single", CommandPermission.General },
        { "Data_Container.InvokeUserCode_CmdResetFirstCustomer", CommandPermission.General },
        { "Data_Container.InvokeUserCode_CmdCloseCheckout", CommandPermission.General },
        { "Data_Container.InvokeUserCode_CmdRequestCloseState", CommandPermission.General },
        { "DebtManager.InvokeUserCode_CmdRequestInvoiceGeneration", CommandPermission.General },
        { "DebtManager.InvokeUserCode_CmdRequestLoan__Int32__Int32__Int32", CommandPermission.General },
        { "DebtManager.InvokeUserCode_CmdPayInvoice__Int32", CommandPermission.General },
        { "DecorationExtraData.InvokeUserCode_CmdChangeColor__Int32", CommandPermission.General },
        { "DecorationExtraData.InvokeUserCode_CmdChangeText__String", CommandPermission.General },
        { "DemolishableManager.InvokeUserCode_CmdDemolishItem__Int32__Int32", CommandPermission.General },
        { "DemolishDebrisControl.InvokeUserCode_CmdRemoveDebris__Int32", CommandPermission.General },
        { "DrawTheWordManager.InvokeUserCode_CmdEnablePaintingMinigame", CommandPermission.General },
        { "DrawTheWordManager.InvokeUserCode_CmdRequestGameStart__String__GameObject", CommandPermission.General },
        { "DrawTheWordManager.InvokeUserCode_CmdSwapBrushColor__Int32", CommandPermission.General },
        { "DrawTheWordManager.InvokeUserCode_CmdSwapBrushSize__Single", CommandPermission.General },
        { "DrawTheWordManager.InvokeUserCode_CmdSendBrushInformation__Boolean__Vector3", CommandPermission.General },
        { "EasterBehaviour.InvokeUserCode_CmdFredString", CommandPermission.General },
        { "EasterBehaviour.InvokeUserCode_CmdFredWalkState__Boolean", CommandPermission.General },
        { "EasterChecker.InvokeUserCode_CmdSpawnEaster__Int32", CommandPermission.General },
        { "EventCageSpawnNets.InvokeUserCode_CmdDepositAnimalInside__Int32", CommandPermission.General },
        { "GameData.InvokeUserCode_CmdAlterFunds__Single", CommandPermission.General },
        { "GameData.InvokeUserCode_CmdAlterFundsWithoutExperience__Single", CommandPermission.General },
        { "GameData.InvokeUserCode_CmdAcquireFranchise__Int32", CommandPermission.General },
        { "GameData.InvokeUserCode_CmdOpenSupermarket", CommandPermission.General },
        { "GameData.InvokeUserCode_CmdEndDayFromButton", CommandPermission.General },
        { "GameData.InvokeUserCode_CmdmoneySpentOnProducts__Single", CommandPermission.General },
        { "GameData.InvokeUserCode_CmdHostDisconnect", CommandPermission.General },
        { "HalloweenGhost.InvokeUserCode_CmdHitFromPlayer__Vector3", CommandPermission.General },
        { "ManagerBlackboard.InvokeUserCode_CmdAddProductToSpawnList__Int32", CommandPermission.General },
        { "ManagerBlackboard.InvokeUserCode_CmdSpawnBoxEmpty", CommandPermission.General },
        { "ManagerBlackboard.InvokeUserCode_CmdSpawnBoxFromPlayer__Vector3__Int32__Int32__Single", CommandPermission.General },
        { "MiniTransportBehaviour.InvokeUserCode_CmdRequestOwnership__GameObject", CommandPermission.General },
        { "MiniTransportBehaviour.InvokeUserCode_CmdRemoveOwnership", CommandPermission.General },
        { "MiniTransportBehaviour.InvokeUserCode_CmdOnPeopleHit__Vector3", CommandPermission.General },
        { "MiniTransportBehaviour.InvokeUserCode_CmdCollisionHit__Vector3__Single", CommandPermission.General },
        { "MiniTransportBehaviour.InvokeUserCode_CmdHorn", CommandPermission.General },
        { "MiniTransportBehaviour.InvokeUserCode_CmdUpdateArrayValuesStorage__Int32__Int32__Int32", CommandPermission.General },
        { "MisterGift.InvokeUserCode_CmdPlayerTookIt", CommandPermission.General },
        { "MisterGrusch.InvokeUserCode_CmdHitFromPlayer", CommandPermission.General },
        { "NetworkSpawner.InvokeUserCode_CmdSpawn__Int32__Vector3__Vector3", CommandPermission.General },
        { "NetworkSpawner.InvokeUserCode_CmdSpawnProp__Int32__Vector3__Vector3", CommandPermission.General },
        { "NetworkSpawner.InvokeUserCode_CmdSpawnDecoration__Int32__Vector3__Vector3", CommandPermission.General },
        { "NetworkSpawner.InvokeUserCode_CmdObjectMove__GameObject__Vector3__Quaternion", CommandPermission.General },
        { "NetworkSpawner.InvokeUserCode_CmdSpawnBox__Int32__Vector3__Int32__Int32", CommandPermission.General },
        { "NetworkSpawner.InvokeUserCode_CmdSpawnTrayFromPlayer__Vector3__String__Single", CommandPermission.General },
        { "NetworkSpawner.InvokeUserCode_CmdSpawnOrderBoxFromPlayer__Vector3__Single__String__String__String", CommandPermission.General },
        { "NetworkSpawner.InvokeUserCode_CmdDestroyBox__GameObject", CommandPermission.General },
        { "NetworkSpawner.InvokeUserCode_CmdSetSupermarketText__String", CommandPermission.General },
        { "NetworkSpawner.InvokeUserCode_CmdSetSupermarketColor__Color", CommandPermission.General },
        { "PlayerNetwork.InvokeUserCode_CmdCrouch__Boolean", CommandPermission.General },
        { "PlayerNetwork.InvokeUserCode_CmdSetBoxColorToEveryone__Int32", CommandPermission.General },
        { "PlayerNetwork.InvokeUserCode_CmdUpdateTrayToEveryone__String", CommandPermission.General },
        { "PlayerNetwork.InvokeUserCode_CmdChangeCharacter__Int32", CommandPermission.General },
        { "PlayerNetwork.InvokeUserCode_CmdChangeHat__Int32", CommandPermission.General },
        { "PlayerNetwork.InvokeUserCode_CmdChangeEquippedItem__Int32", CommandPermission.General },
        { "PlayerNetwork.InvokeUserCode_CmdPlayAnimation__Int32", CommandPermission.General },
        { "PlayerNetwork.InvokeUserCode_CmdDebtCollectorAchievement", CommandPermission.General },
        { "PlayerNetwork.InvokeUserCode_CmdPushPlayer__Vector3", CommandPermission.General },
        { "PlayerNetwork.InvokeUserCode_CmdPlayPricingSound", CommandPermission.General },
        { "PlayerNetwork.InvokeUserCode_CmdPlayPose__Int32", CommandPermission.General },
        { "PlayerObjectController.InvokeUserCode_CmdSendMessage__String__NetworkConnectionToClient", CommandPermission.General },
        { "PlayerObjectController.InvokeUserCode_CmdSetPlayerName__String", CommandPermission.General },
        { "NetworkGameBehaviors.InvokeUserCode_CmdServerEnableVoiceChat", CommandPermission.General },
        { "NetworkGameBehaviors.InvokeUserCode_CmdRefreshStatus", CommandPermission.General },
        { "NPC_Info.InvokeUserCode_CmdAnimationPlay__Int32", CommandPermission.General },
        { "NPC_Info.InvokeUserCode_CmdSurveillanceSet", CommandPermission.General },
        { "NPC_Manager.InvokeUserCode_CmdUpdateRecycleStatus", CommandPermission.General },
        { "NPC_Manager.InvokeUserCode_CmdRequestRecycleStatus", CommandPermission.General },
        { "NPC_Manager.InvokeUserCode_CmdRerollCall", CommandPermission.General },
        { "NPC_Manager.InvokeUserCode_CmdHireEmployeeData__Int32__String", CommandPermission.General },
        { "NPC_Manager.InvokeUserCode_CmdDismissEmployeeData__Int32", CommandPermission.General },
        { "NPC_Manager.InvokeUserCode_CmdRequestHappinessLevel", CommandPermission.General },
        { "NPC_Manager.InvokeUserCode_CmdChangeEmployeeName__Int32__String", CommandPermission.General },
        { "NPC_Manager.InvokeUserCode_CmdChangeEmployeeHat__Int32__Int32", CommandPermission.General },
        { "NPC_Manager.InvokeUserCode_CmdChangeEmployeePriority__Int32__Int32", CommandPermission.General },
        { "NPC_Manager.InvokeUserCode_CmdChangeAllEmployeePriorities__Int32", CommandPermission.General },
        { "NPC_Manager.InvokeUserCode_CmdLoadPrioritiesLayout__Int32[]", CommandPermission.General },
        { "OrderPackaging.InvokeUserCode_CmdActivateOrderDepartment", CommandPermission.General },
        { "OrderPackaging.InvokeUserCode_CmdEnableOrderNotifications", CommandPermission.General },
        { "OrderPackaging.InvokeUserCode_CmdAssignOrderToTable__Int32__Int32", CommandPermission.General },
        { "OrderPackaging.InvokeUserCode_CmdCreateBoxOrder__Int32__String", CommandPermission.General },
        { "OrderPackaging.InvokeUserCode_CmdAddItemToTable__Int32__GameObject__Int32", CommandPermission.General },
        { "OrderPackaging.InvokeUserCode_CmdRemoveItemFromTable__Int32__GameObject__Int32", CommandPermission.General },
        { "OrderPickupPoint.InvokeUserCode_CmdAddOrderBox__Int32__String", CommandPermission.General },
        { "OtherPropsBehaviour.InvokeUserCode_CmdURLRequested__String", CommandPermission.General },
        { "OtherPropsBehaviour.InvokeUserCode_CmdUpdateDoorSetter__Int32", CommandPermission.General },
        { "PaintableDecoration.InvokeUserCode_CmdSetPaintable__Int32__Int32", CommandPermission.General },
        { "PaintablesManager.InvokeUserCode_CmdUpdateSingleParentMaterial__Int32__Int32__Int32__Int32", CommandPermission.General },
        { "PictureFrameBehaviour.InvokeUserCode_CmdChangeURL__String", CommandPermission.General },
        { "PictureFrameBehaviour.InvokeUserCode_CmdSetPictureSize__Single__Single", CommandPermission.General },
        { "PictureFrameBehaviour.InvokeUserCode_CmdChangeDefaultImage__Int32", CommandPermission.General },
        { "ProductCheckoutSpawn.InvokeUserCode_CmdAddProductValueToCheckout", CommandPermission.General },
        { "ProductListing.InvokeUserCode_CmdUpdateProductPrice__Int32__Single", CommandPermission.General },
        { "ProductListing.InvokeUserCode_CmdUnlockProductTier__Int32", CommandPermission.General },
        { "ProductListing.InvokeUserCode_CmdSetProductOnSale__Int32__Int32", CommandPermission.General },
        { "SeasonalCageEventAnimal.InvokeUserCode_CmdHitFromPlayer__GameObject", CommandPermission.General },
        { "StolenProductSpawn.InvokeUserCode_CmdRecoverStolenProduct", CommandPermission.General },
        { "TrashSpawn.InvokeUserCode_CmdClearTrash", CommandPermission.General },
        { "UpgradesManager.InvokeUserCode_CmdAddSpace__Int32", CommandPermission.General },
        { "UpgradesManager.InvokeUserCode_CmdAddStorage__Int32", CommandPermission.General },
        { "UpgradesManager.InvokeUserCode_CmdAddAddon__Int32", CommandPermission.General },
        { "UpgradesManager.InvokeUserCode_CmdAcquirePerk__Int32__Int32", CommandPermission.General },
        { "UpgradesManager.InvokeUserCode_CmdTimeAcceleration", CommandPermission.General },
        { "UpgradesManager.InvokeUserCode_CmdChangeTimeAcceleration__Boolean", CommandPermission.General },
        { "ServerAuthorityExamplePlayerController.InvokeUserCode_CmdTeleport", CommandPermission.General },
        { "ServerAuthorityExamplePlayerController.InvokeUserCode_CmdMove__KeyCode", CommandPermission.General },
        { "Smooth.SmoothSyncMirror.InvokeUserCode_CmdTeleport__Vector3__Vector3__Vector3__Single", CommandPermission.General },
        { "Dissonance.Integrations.MirrorIgnorance.MirrorIgnorancePlayer.InvokeUserCode_CmdSetPlayerName__String", CommandPermission.General } };
}
